# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            AI4HR&PES
tagline:          ''
description:      'International workshop on AI for Human Resources and Public Employment Services'
url:              https://feast-ecmlpkdd.github.io/
baseurl:          ''
destination:      _site

author:
  name:           'Bo Kang'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/feast-ecmlpkdd/website

plugins:
  - jekyll-paginate
  - jekyll-gist

